# Generated by Django 6.0.4 on 2026-05-12 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0003_author_publisher_lab9book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmodule.address'),
        ),
    ]
